### PR TITLE
Doc and tests

### PR DESCRIPTION
**Pull request by TornaxO7**
- Moved the tests of the `src/msg/model.rs` file to the `tests` directory to make use of its purpose :D
- Also added more tests and documentation
- Also fixed some tests to make them pass.

### CODE REVIEW

**Comment by TornaxO7** [comment]
@soywod review pls

**Comment by TornaxO7** [comment]
Oh man, I just forgot that I should do the last two points... sorry! I'm closing this now.

**Comment by soywod** [comment]
> Moved the tests of the `src/msg/model.rs` file to the `tests` directory to make use of its purpose :D

In fact, the `tests` folder is for integration tests. Unit tests should stay next to the model, see https://doc.rust-lang.org/book/ch11-03-test-organization.html.

**Comment by TornaxO7** [comment]
@soywod by the way, could you please give me reproduction steps for the reply and forwarding of a message? Because if I do a reply (just `cargo run -- reply <id>`) or forwarding (just `cargo run -- forward <id>`) the  body of the previous message is included.

**Comment by soywod** [comment]
I cannot reproduce either, I guess it has been fixed meanwhile (or I wrongly tested). So you can forget those points!

**Comment by TornaxO7** [comment]
:+1: Alright, where can I help you then?

**Comment by soywod** [comment]
Mmmh I guess I need to fix first my part, then we can check together what to do. Now that I browsed a bit your code, I have some point to see with you (kind of questions / adjustments).

**Pull request closed without merging**
