### PR TITLE
The sender is not displayed properly in table and json

### PR DESCRIPTION
**Pull request by TornaxO7**
Last one!

### CODE REVIEW

**Review by soywod — APPROVED** [review]

**Comment by TornaxO7** [comment]
@soywod could you please test it for a moment? I'm unsure if that's gonna fix the issue and I'm also unsure how to test it.

**Comment by TornaxO7** [comment]
I mean the issue with the rfc-encoding

**Comment by soywod** [comment]
Seems to work better, I approve!

**Comment by TornaxO7** [comment]
Stonks!

**Pull request merged**
